### ISSUE TITLE
Style is broken

### ISSUE THREAD

**Issue by tonatiuh** [fukayatsu/easy-copy-for-pivotal-tracker#4]
The style seems to be broken, instead of showing the yellow background it shows no background and a red color text.

Here is an screenshot ![broken style](http://oi59.tinypic.com/2v2efx2.jpg)

**Comment by fukayatsu** [comment]
@tonatiuh thanks for reporting! I'll fix this soon.

**Comment by fukayatsu** [comment]
I've just published v0.2.7 :)
It will be available in an hour.
